Make cert.pl use the useless runes files the same way as 'make' does.
acl2/acl2 pull request #1337
Opened 2022-01-06 06:18 UTC by bendyarm

Prior to this if you use `cert.pl` to certify a book,
and if the environment variable `ACL2_USELESS_RUNES`
is not defined and exported, then `cert.pl` ignores
the useless runes files.

After this PR, `cert.pl` looks at `ACL2_USELESS_RUNES`
and if it is not defined, it sets it to -25, which is the default
for `make` in the community books directory.

One common use case that this speeds up a lot is when
you want to work on a particular book (whether that is in
the community books or not), and you want to certify all
of its dependencies without doing a full regression.
It is convenient to just do `cert.pl oracle` or some such command, 
but if there are any slow community books that need to be certified,
this could take longer than doing the full regression due to
`cert.pl` ignoring the useless runes files.

2022-01-06 12:50 UTC, MattKaufmann requested changes
Suppose ACL2_USELESS_RUNES is set to the empty string as noted for example in :DOC verify-guards-for-system-functions: "ACL2_USELESS_RUNES= ".  Will this do the right thing, or does the new !defined check need to be disjoined with a check for the empty string?

Also, please update :doc build::cert.pl or an appropriate subtopic accordingly.

2022-01-06 19:12 UTC, acoglio approved these changes
This looks like an improvement to me. Thanks!

2022-01-06 19:36 UTC, ericwhitmansmith commented
Having `cert.pl` do the same thing as `make` wrt useless runes seems like a good idea to me.

2022-01-06 21:23 UTC, solswords approved these changes
I think this is fine. Arguably it could be done in only one place (make_cert or make_cert_help.pl or in ACL2 itself) rather than both here and in Makefile-features (via cert_features.lsp), but probably not worth untangling it all if this works.

2022-01-08 00:09 UTC, bendyarm commented
> Suppose ACL2_USELESS_RUNES is set to the empty string as noted for example in :DOC verify-guards-for-system-functions: "ACL2_USELESS_RUNES= ". Will this do the right thing, or does the new !defined check need to be disjoined with a check for the empty string?
> 
> Also, please update :doc build::cert.pl or an appropriate subtopic accordingly.

I believe it will "do the right thing", but the phrase
"because of how proofs differ" gives me pause.

Question: is the point of doing `ACL2_USELESS_RUNES= `
in the `make .. devel-check.cert` to turn off useless runes file processing?
By preventing the `export ACL2_USELESS_RUNES ?= -25` in `Makefile-features`
from setting it to -25?

If so, then I think this logic in cert.pl is the same.  Here is some evidence.
Take the following perl file, and put it in a temporary testing directory:
```
#!/usr/bin/env perl                                                                                                                                                                                                                                                                                                                                                                             

print "before:\n";
print "\$ENV{\"ACL2_USELESS_RUNES\"} exists: " . (exists $ENV{"ACL2_USELESS_RUNES"} ? "yes" : "no") . "\n";
print "\$ENV{\"ACL2_USELESS_RUNES\"} is defined: " . (defined $ENV{"ACL2_USELESS_RUNES"} ? "yes" : "no") . "\n";
if ( defined $ENV{"ACL2_USELESS_RUNES"} ) {
    print "Value is " . $ENV{"ACL2_USELESS_RUNES"} . "\n";
}

print $ENV{'ACL2_USELESS_RUNES'};
print "\n";

if (! defined($ENV{"ACL2_USELESS_RUNES"}) ) {
    $ENV{"ACL2_USELESS_RUNES"} = "-25";
}

print "after:\n";
print "\$ENV{\"ACL2_USELESS_RUNES\"} exists: " . (exists $ENV{"ACL2_USELESS_RUNES"} ? "yes" : "no") . "\n";
print "\$ENV{\"ACL2_USELESS_RUNES\"} is defined: " . (defined $ENV{"ACL2_USELESS_RUNES"} ? "yes" : "no") . "\n";
if ( defined $ENV{"ACL2_USELESS_RUNES"} ) {
    print "Value is " . $ENV{"ACL2_USELESS_RUNES"} . "\n\n";
}
```
Then run it with various values of `ACL2_USELESS_RUNES` to see what it does.  I get this:
```
$ unset ACL2_USELESS_RUNES                                                                                                                                                                                                                                                                                                     
$ perl tpl.pl                                                                                                                                                                                                                                                                                                                  
before:                                                                                                                                                                                                                                                                                                                        
$ENV{"ACL2_USELESS_RUNES"} exists: no                                                                                                                                                                                                                                                                                          
$ENV{"ACL2_USELESS_RUNES"} is defined: no                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                               
after:                                                                                                                                                                                                                                                                                                                         
$ENV{"ACL2_USELESS_RUNES"} exists: yes                                                                                                                                                                                                                                                                                         
$ENV{"ACL2_USELESS_RUNES"} is defined: yes                                                                                                                                                                                                                                                                                     
Value is -25          
                                                                                                                                                                                                                                                                                                         
$ ACL2_USELESS_RUNES= perl tpl.pl                                                                                                                                                                                                                                                                                              
before:                                                                                                                                                                                                                                                                                                                        
$ENV{"ACL2_USELESS_RUNES"} exists: yes                                                                                                                                                                                                                                                                                         
$ENV{"ACL2_USELESS_RUNES"} is defined: yes                                                                                                                                                                                                                                                                                     
Value is                                                                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                               
after:                                                                                                                                                                                                                                                                                                                         
$ENV{"ACL2_USELESS_RUNES"} exists: yes                                                                                                                                                                                                                                                                                         
$ENV{"ACL2_USELESS_RUNES"} is defined: yes                                            [...]

2022-01-08 00:29 UTC, MattKaufmann commented
@bendyarm Sorry about any confusion.  Yes, I agree that your new code looks right (and, the answer to your question is "yes").  So all that's left is to update :doc build::cert.pl or an appropriate subtopic accordingly.

2022-01-09 02:07 UTC, bendyarm commented
There is still some discussion on Slack about how to handle this for ACL2(r) and maybe ACL2(p) so we should not merge this PR until we decide that and update the doc accordingly.

2022-01-13 06:16 UTC, bendyarm commented
Superseded by cert-heed-useless-runes-2; closing.

2022-01-13 06:16 UTC, closed without merging