[Std/typed-lists] Add a rule and rename another rule.
acl2/acl2 pull request #1465
Opened 2023-02-25 03:31 UTC by acoglio

The new rule backchains from `true-listp` to `symbol-listp` without limit; it is disabled by default.

The renamed rule is one that backchains at most once, and is enabled.

It seems that using the unqualified `true-listp-when-symbol-listp-rewrite` for the first rule is more consistent with other libraries. This is the reason for renaming the second rule in a way that describes its specific characteristics.

2023-02-25 18:18 UTC, solswords approved these changes

2023-02-25 20:54 UTC, ericwhitmansmith requested changes
It looks like the backchain limit didn't actually get removed from the second rule.

2023-02-25 23:55 UTC, acoglio commented
Yes, no kidding (!). I just pushed a commit to rectify that.

2023-02-26 00:11 UTC, ericwhitmansmith approved these changes

2023-02-26 01:16 UTC, acoglio commented
@ericwhitmansmith Now you can rename this:
https://github.com/acl2/acl2/blob/5c5902e96c39239634c6c5fc1490160813c293db/books/kestrel/typed-lists-light/symbol-listp.lisp#L124-L127

2023-02-26 01:16 UTC, merged