Create pdf-grammar.txt
acl2/acl2 pull request #1521
Opened 2023-07-24 14:10 UTC by lwli11

These requests add the ABNF pdf grammar and wrapper lisp function that parses and checks that the rules are closed.

2023-07-24 21:17 UTC, ericwhitmansmith commented
Please change to target the acl2:testing branch instead.  See https://www.cs.utexas.edu/users/moore/acl2/manuals/latest/?topic=ACL2____GITHUB-COMMIT-CODE-USING-PULL-REQUESTS

2023-07-24 21:20 UTC, lwli11 commented
Ok, I'm trying again. I don't know where the infinite files came from.

2023-07-24 21:22 UTC, MattKaufmann commented
This needs to go to testing instead of master.  It appears still to be targeted to master.  The "infinite files" were for a different pull request from you (#1522), by the way.

2023-07-25 02:22 UTC, acoglio commented on books/kestrel/abnf/examples/pdf-grammar.txt
> +
There's an extra blank line and the `%x00` is further right than the other codes. Can the layout be made more uniform?

2023-07-25 02:23 UTC, acoglio requested changes
Thank you so much for this addition. Would you mind remind this file to `pdf.abnf`, or consistency with the other grammar files in this directory? (One benefit of using an `.abnf` extension is that GitHub shows ABNF syntax highlighting.)

2023-07-25 12:11 UTC, lwli11 commented
Thanks for working with me to merge all these changes! I've renamed the changes and figured out how to add the wrapper pdf.lisp to this merge request as well.

2023-07-27 01:19 UTC, acoglio approved these changes

2023-07-27 01:19 UTC, merged