Add test cases for c$ preprocessing utility
acl2/acl2 pull request #1595
Opened 2024-05-28 17:43 UTC by gjurgensen

Since the preprocessing utility is open-ended in its system dependencies, I've added the cert_param flag "uses-preprocessor" as well as the Makefile variable "USE_PREPROCESSOR" to control certification of books using the tool, such as this new test book.

The feature does not attempt to auto-detect dependencies, and defaults to "off". Thus, you must explicitly set `USE_PREPROCESSOR=1` when invoking make to build the relevant books.

The names of these variables is easy to change. We might consider renaming it to "USE_C_PREPROCESSOR" to be more specific. Or "USE_C_UTILITIES" if we expect other similar utilities to require conditional certification.

2024-05-28 20:06 UTC, acoglio requested changes
Since 'preprocessor' sounds generic, I suggest using 'cpreprocessor' for clarity/specificity, in the Makefile, environment variable, and certification flag.

The rest looks fine.

2024-05-28 20:07 UTC, acoglio commented
Adding two more reviewers since this affects the books makefile as well. @solswords @ericwhitmansmith

2024-05-28 22:31 UTC, solswords approved these changes

2024-05-29 16:38 UTC, gjurgensen commented
@acoglio 
> Since 'preprocessor' sounds generic, I suggest using 'cpreprocessor' for clarity/specificity, in the Makefile, environment variable, and certification flag.

I changed the names to "uses-c-preprocessor" and "USE_C_PREPROCESSOR".

2024-05-29 19:06 UTC, gjurgensen commented
For simplicity, I switched to "uses-cpp" and "OS_HAS_CPP", which is set by autodetecting availability of "cpp".

2024-05-29 19:30 UTC, acoglio commented on books/kestrel/c/syntax/preprocess-file.lisp
> +      default preprocessor \"cpp\", certification may controlled with the the
```suggestion
      default preprocessor \"cpp\", certification may be controlled with the the
```

2024-05-29 19:30 UTC, acoglio approved these changes

2024-05-30 01:43 UTC, ericwhitmansmith approved these changes

2024-06-01 01:43 UTC, merged